# Generated by Django 3.2.3 on 2021-05-17 05:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shortener_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='shortened_url',
        ),
        migrations.AddField(
            model_name='url',
            name='shortened_slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
