# Generated by Django 3.2.3 on 2021-05-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener_app', '0002_auto_20210517_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='shortened_slug',
            field=models.SlugField(max_length=200),
        ),
    ]
