# Generated by Django 3.2.3 on 2021-05-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener_app', '0003_alter_url_shortened_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='shortened_slug',
        ),
        migrations.AddField(
            model_name='url',
            name='shortened_url',
            field=models.CharField(default=None, max_length=200, unique=True),
        ),
    ]
